"""Add missing tables like trade_memories

Revision ID: 7a66cbb55ec9
Revises: 915d37ce4bad
Create Date: 2026-08-08 19:41:18.654453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a66cbb55ec9'
down_revision: Union[str, Sequence[str], None] = '915d37ce4bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_memories',
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('pattern', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('key_lessons', sa.JSON(), nullable=True),
    sa.Column('do_rules', sa.JSON(), nullable=True),
    sa.Column('dont_rules', sa.JSON(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id')
    )
    op.create_index('ix_trade_memories_outcome', 'trade_memories', ['outcome'], unique=False)
    op.create_index('ix_trade_memories_symbol_regime', 'trade_memories', ['symbol', 'regime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_memories_symbol_regime', table_name='trade_memories')
    op.drop_index('ix_trade_memories_outcome', table_name='trade_memories')
    op.drop_table('trade_memories')
    # ### end Alembic commands ###
