"""initial schema: 15 tables

Revision ID: 915d37ce4bad
Revises: 
Create Date: 2026-08-07 19:17:07.164569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915d37ce4bad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('event_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_event_time', ['event_time_utc'], unique=False)

    op.create_table('candles',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('open_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('volume', sa.Numeric(precision=32, scale=12), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=32, scale=12), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'symbol', 'timeframe', 'open_time_utc', name='uq_candles_provider_symbol_timeframe_open')
    )
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.create_index('ix_candles_lookup', ['symbol', 'timeframe', 'open_time_utc'], unique=False)

    op.create_table('data_quality_reports',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('assessed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('bars_checked', sa.Integer(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('failures', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_reports', schema=None) as batch_op:
        batch_op.create_index('ix_quality_symbol_time', ['symbol', 'assessed_at_utc'], unique=False)

    op.create_table('economic_events',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('event_id_from_provider', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('scheduled_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual', sa.String(length=64), nullable=True),
    sa.Column('forecast', sa.String(length=64), nullable=True),
    sa.Column('previous', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_time_currency', ['scheduled_utc', 'currency'], unique=False)

    op.create_table('feature_snapshots',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('as_of_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bars_used', sa.Integer(), nullable=False),
    sa.Column('indicator_version', sa.String(length=32), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('unavailable', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'as_of_utc', name='uq_features_symbol_timeframe_time')
    )
    op.create_table('news_items',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('published_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index('ix_news_published', ['published_at_utc'], unique=False)

    op.create_table('provider_health',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('checked_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('credential_present', sa.Boolean(), nullable=False),
    sa.Column('endpoint_reachable', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_health', schema=None) as batch_op:
        batch_op.create_index('ix_provider_health_provider_time', ['provider', 'checked_at_utc'], unique=False)

    op.create_table('provider_quota',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('window_kind', sa.String(length=16), nullable=False),
    sa.Column('window_start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requests_made', sa.Integer(), nullable=False),
    sa.Column('requests_allowed', sa.Integer(), nullable=True),
    sa.Column('last_request_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'window_kind', 'window_start_utc', name='uq_provider_quota_window')
    )
    op.create_table('quotes',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('as_of_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('ask', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('mid', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('last', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('spread_absolute', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('spread_basis_points', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index('ix_quotes_symbol_time', ['symbol', 'as_of_utc'], unique=False)

    op.create_table('regime_reports',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('as_of_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime_version', sa.String(length=32), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('heuristic_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('contradictions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'as_of_utc', name='uq_regime_symbol_timeframe_time')
    )
    op.create_table('scan_results',
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('scanned_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('symbols_scanned', sa.Integer(), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('rejections_logged', sa.Integer(), nullable=False),
    sa.Column('runtime_ms', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.create_index('ix_scan_results_scanned_at', ['scanned_at_utc'], unique=False)

    op.create_table('settled_signals',
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('settlement_price', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('expiry_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settlement_provider', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    with op.batch_alter_table('settled_signals', schema=None) as batch_op:
        batch_op.create_index('ix_settled_signals_settled_at', ['settled_at_utc'], unique=False)

    op.create_table('signals',
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('signal_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('llm_response', sa.JSON(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_symbol_time', ['symbol', 'signal_time_utc'], unique=False)

    op.create_table('structure_reports',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('as_of_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bars_used', sa.Integer(), nullable=False),
    sa.Column('structure_version', sa.String(length=32), nullable=False),
    sa.Column('structure_label', sa.String(length=32), nullable=False),
    sa.Column('breakout_candidate', sa.Boolean(), nullable=False),
    sa.Column('breakout_direction', sa.String(length=16), nullable=True),
    sa.Column('failed_breakout', sa.Boolean(), nullable=False),
    sa.Column('nearest_support', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('nearest_resistance', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('swing_highs', sa.JSON(), nullable=True),
    sa.Column('swing_lows', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'as_of_utc', name='uq_structure_symbol_timeframe_time')
    )
    op.create_table('symbols',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=32), nullable=True),
    sa.Column('quote_asset', sa.String(length=32), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('quantity_precision', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Numeric(precision=32, scale=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enabled_for_scanning', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'symbol', name='uq_symbols_provider_symbol')
    )
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.create_index('ix_symbols_asset_class', ['asset_class'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.drop_index('ix_symbols_asset_class')

    op.drop_table('symbols')
    op.drop_table('structure_reports')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index('ix_signals_symbol_time')

    op.drop_table('signals')
    with op.batch_alter_table('settled_signals', schema=None) as batch_op:
        batch_op.drop_index('ix_settled_signals_settled_at')

    op.drop_table('settled_signals')
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_results_scanned_at')

    op.drop_table('scan_results')
    op.drop_table('regime_reports')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_quotes_symbol_time')

    op.drop_table('quotes')
    op.drop_table('provider_quota')
    with op.batch_alter_table('provider_health', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_health_provider_time')

    op.drop_table('provider_health')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index('ix_news_published')

    op.drop_table('news_items')
    op.drop_table('feature_snapshots')
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_time_currency')

    op.drop_table('economic_events')
    with op.batch_alter_table('data_quality_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_quality_symbol_time')

    op.drop_table('data_quality_reports')
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_index('ix_candles_lookup')

    op.drop_table('candles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_event_time')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
